TakeaNote.UI/Controllers/FraseController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using TakeaNote.Application.Contracts;
using TakeaNote.Domain.DomainEntities;
using TakeaNote.UI.Models;
using TakeaNote.Util.Resources;

namespace TakeaNote.UI.Controllers
{
    [Authorize(Roles = "M, A, U")]
    public class FraseController : BaseController
    {
        private readonly IFraseAppService fraseAppService;
        private readonly ICategoriaAppService categoriaAppService;
        private readonly IUsuarioAppService usuarioAppService;
        private readonly int pageSize = int.Parse(ConfigurationManager.AppSettings["MAX_ELEMENTOS_PAGINA"]);

        public FraseController(IFraseAppService fraseAppService, ICategoriaAppService categoriaAppService,
            IUsuarioAppService usuarioAppService)
        {
            this.fraseAppService = fraseAppService;
            this.categoriaAppService = categoriaAppService;
            this.usuarioAppService = usuarioAppService;
        }

        public ActionResult Cadastrar()
        {
            try
            {
                ViewBag.CategoriasCollection = ObterCategorias();

                return View();
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroFraseViewModel model)
        {
            try
            {
                var userSession = Session["USER_SESSION"] as Usuario;

                if (ModelState.IsValid)
                {
                    var categoriasCollection = new List<Categoria>();

                    if (model.CategoriasSelecionadas != null)
                    {
                        foreach (var id in model.CategoriasSelecionadas)
                        {
                            var categoria = categoriaAppService.FindById(int.Parse(id));
                            categoriasCollection.Add(categoria);
                        }
                    }

                    var frase = new Frase
                    {
                        Descricao = model.Descricao,
                        Autor = model.Autor,
                        Visualizacao = model.Visualizacao,
                        DataCadastro = DateTime.Now,
                        // TODO: Prevenir erro ao trazer possivel id nulo num post forçado
                        IdUsuario = userSession.IdUsuario,
                        ListaCategorias = categoriasCollection
                    };

                    fraseAppService.Insert(frase);

                    MensagensSucesso.Add(Resources.FraseCadastradaSucesso);

                    ModelState.Clear();
                }
                else
                {
                    MensagensErro = GetModelErrors(ModelState);
                }

                ViewBag.CategoriasCollection = categoriaAppService.FindAll();
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);
            }

            return View();
        }

        [Authorize(Roles = "M, A, U")]
        public ActionResult Editar(int id)
        {
            try
            {
                var frase = fraseAppService.ObterFraseComCategorias(id);

                var userSession = Session["USER_SESSION"] as Usuario;

                if (userSession.IdUsuario != frase.IdUsuario)
                {
                    if (userSession.Regra != "M" && userSession.Regra != "A")
                    {
                        throw new Exception(Resources.FraseSemPermissaoEdicao);
                    }
                }

                if (frase != null)
                {
                    // Salva o id atual para prevenir que o usuario nao edite uma frase diferente da selecionada.

                    Session["ID_FRASE_EDITADA"] = frase.IdFrase;

                    var model = new EdicaoFraseViewModel
                    {
                        IdFrase = frase.IdFrase,
                        Descricao = frase.Descricao,
                        Autor = frase.Autor,
                        Visualizacao = frase.Visualizacao,
                    };

                    // Recupera as categorias do bd, e associa as categorias ja atribuidas ao Usuario

                    var categoriasSelecionadasCollection = new List<CategoriasSelecionadasViewModel>();

                    foreach (var item in ObterCategorias())
                    {
                        var x = new CategoriasSelecionadasViewModel
                        {
                            IdCategoria = item.IdCategoria,
                            Nome = item.Nome
                        };

                        // verificar se a mesma pertence ao Usuario, e marca-la como checked
                        foreach (var categoriaUsuario in frase.ListaCategorias)
                        {
                            if (x.IdCategoria == categoriaUsuario.IdCategoria)
                            {
                                x.Checked = true;
                            }
                        }

                        categoriasSelecionadasCollection.Add(x);
                    }

                    model.ListaCategorias = categoriasSelecionadasCollection;

                    return View(model);
                }
                else
                {
                    throw new Exception(Resources.FraseErroCarregarDados);
                }
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "M, A, U")]
        [HttpPost]
        public ActionResult Editar(EdicaoFraseViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    MensagensErro = GetModelErrors(ModelState);

                    return View(model);
                }

                var listaCategorias = new List<Categoria>();

                foreach (var categoria in model.ListaCategorias)
                {
                    if (categoria.Checked)
                    {
                        var c = new Categoria
                        {
                            IdCategoria = categoria.IdCategoria
                        };

                        listaCategorias.Add(c);
                    }
                }

                var frase = new Frase
                {
                    // TODO: Prevenir erro ao trazer possivel id nulo num post forçado
                    IdFrase = (int)Session["ID_FRASE_EDITADA"],
                    Descricao = model.Descricao,
                    Autor = model.Autor,
                    Visualizacao = model.Visualizacao,
                    ListaCategorias = listaCategorias
                };

                fraseAppService.AtualizarFraseComCategorias(frase);

                MensagensSucesso.Add(Resources.FraseAtualizadaSucesso);
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);
            }

            return View(model);
        }

        [Authorize(Roles = "M, A, U, C")]
        public ActionResult Consultar(int? id)
        {
            try
            {
                int pageNumber = (id ?? 1);

                var modelCollection = new List<ConsultaFraseViewModel>();

                foreach (var frase in ObterFrasesComCategorias(pageNumber, pageSize))
                {
                    var model = new ConsultaFraseViewModel
                    {
                        IdFrase = frase.IdFrase,
                        Descricao = frase.Descricao,
                        Autor = frase.Autor,
                        Visualizacao = frase.Visualizacao,
                        DataCadastro = frase.DataCadastro,
                        ListaCategorias = frase.ListaCategorias
                    };

                    modelCollection.Add(model);
                }

                ViewBag.PageNumber = pageNumber;

                return View(modelCollection);
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "M, A, U")]
        public ActionResult Excluir(int id)
        {
            try
            {
                var frase = fraseAppService.ObterFraseComCategorias(id);

                var userSession = Session["USER_SESSION"] as Usuario;

                if (userSession.IdUsuario != frase.IdUsuario)
                {
                    if (userSession.Regra != "M" && userSession.Regra != "A")
                    {
                        throw new Exception(Resources.FraseSemPermissaoExclusao);
                    }
                }

                fraseAppService.DeletarFrase(frase);

                MensagensSucesso.Add(Resources.FraseExcluidaSucesso);

                return RedirectToAction("Consultar");
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        private List<Frase> ObterFrasesComCategorias(int pageNumber, int pageSize)
        {
            try
            {
                ViewBag.TotalPaginas = fraseAppService.ObterFrasesComCategorias().Count() / pageSize;
                return fraseAppService.ObterFrasesComCategorias(pageNumber, pageSize);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        private List<Categoria> ObterCategorias()
        {
            try
            {
                return categoriaAppService.ObterCategoriasComFrases();

TakeaNote.UI/Views/Frase/Cadastrar.cshtml
@model TakeaNote.UI.Models.CadastroFraseViewModel

@{
    ViewBag.Title = "Take a Note | Cadastro";
}

@using (Html.BeginForm("Cadastrar", "Frase", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row mt-5">

        @{ Html.RenderPartial("Mensagens"); }

        <div class="form-horizontal col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label" })
                <div>
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label " })
                <div>
                    @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Visualizacao, htmlAttributes: new { @class = "control-label " })
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "P", new { @id = "rdbVisualizacaoPublica", @class = "custom-control-input", @checked = "checked" })
                    <label class="custom-control-label" for="rdbVisualizacaoPublica">Pública</label>
                </div>
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "R", new { @id = "rdbVisualizacaoRestrita", @class = "custom-control-input" })
                    <label class="custom-control-label" for="rdbVisualizacaoRestrita">Restrita</label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 ">
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                    <a href="@Url.Content("/Home/Index")" class="btn btn-outline-dark">Voltar</a>
                </div>
            </div>

            <label class="control-label">
                Associar com Categorias
            </label>

            @if (ViewBag.CategoriasCollection != null && ViewBag.CategoriasCollection.Count > 0)
            {
                foreach (var item in ViewBag.CategoriasCollection)
                {
                    <div class="custom-control custom-checkbox">
                        <input class="custom-control-input" id="@item.IdCategoria" type="checkbox" name="CategoriasSelecionadas" value="@item.IdCategoria" />
                        <label class="custom-control-label" for="@item.IdCategoria">@item.Nome</label>
                    </div>
                }
            }

        </div>
    </div>
}

TakeaNote.UI/Views/Frase/Consultar.cshtml
@using TakeaNote.Domain.DomainEntities

@{
    Usuario usuario = Session["USER_SESSION"] as Usuario;
    ViewBag.Title = "Take a Note | Consultar Frases";
    string corBadge = "";
}

@model IEnumerable<TakeaNote.UI.Models.ConsultaFraseViewModel>

<div class="row mt-5">

    @{ Html.RenderPartial("Mensagens"); }

    <div class="form-horizontal col-md-12 text-center">
        <a href="@Url.Action("Consultar", "Frase", new { id = 1 })" class="btn btn-sm btn-primary">Primeira</a>
        <a href="@Url.Action("Consultar", "Frase", new { id = ViewBag.PageNumber - 1 })" class="btn btn-sm btn-primary">Anterior</a>
        <a href="@Url.Action("Consultar", "Frase", new { id = ViewBag.PageNumber + 1 })" class="btn btn-sm btn-primary">Proxima</a>
        <a href="@Url.Action("Consultar", "Frase", new { id = ViewBag.TotalPaginas })" class="btn btn-sm btn-primary">última</a>
    </div>

    <br />
    <br />

    <div class="form-horizontal col-md-12">

        @foreach (var frase in Model)
        {
            if (frase.Visualizacao == "P")
            {
                corBadge = "alert-info";
            }
            else
            {
                corBadge = "alert-danger";
            }

            <div id="accordion">
                <div class="card shadow">
                    <div class="card-header bg-transparent" id="heading_@frase.IdFrase" style="padding-bottom:5px; padding-top:10px">
                        <h6 class="mb-0">
                            <btn class="btn btn-link text-primary text-dark" style="text-decoration:none" data-toggle="collapse" data-target="#linha_@frase.IdFrase" aria-expanded="true" aria-controls="linha_@frase.IdFrase">
                                @frase.Descricao
                            </btn>
                            <span class="badge badge-pill float-right @corBadge">
                                @frase.Visualizacao
                            </span>
                        </h6>
                    </div>

                    <div id="linha_@frase.IdFrase" class="collapse" aria-labelledby="heading_@frase.IdFrase" data-parent="#accordion">
                        <div class="card-body">
                            <span class="card-subtitle mb-2 text-muted">@frase.Autor</span>
                            <hr />

                            <div>
                                @foreach (var categoria in frase.ListaCategorias)
                                {
                                    <span class="badge badge-pill badge-dark">
                                        @categoria.Nome
                                    </span>
                                }
                            </div>
                            <hr />

                            <a href="@Url.Action("Editar", "Frase", new { id = frase.IdFrase })" class="btn btn-sm btn-primary">Editar</a>

                            @Html.ActionLink("Excluir", "Excluir",
                                new { id = frase.IdFrase },
                                new { onclick = "return confirm('Tem certeza que deseja excluir?')", @class = "btn btn-sm btn-dark" })
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

TakeaNote.UI/Views/Frase/Editar.cshtml
@using TakeaNote.Domain.DomainEntities

@{
    Usuario usuario = Session["USER_SESSION"] as Usuario;
}

@model TakeaNote.UI.Models.EdicaoFraseViewModel

@{
    ViewBag.Title = "Take a Note | Editar Frase";
}

@using (Html.BeginForm("Editar", "Frase", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row mt-5">

        @{ Html.RenderPartial("Mensagens"); }

        <div class="form-horizontal col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Autor, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.Autor, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Visualizacao, htmlAttributes: new { @class = "control-label " })
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "P", new { @id = "rdbVisualizacaoPublica", @class = "custom-control-input" })
                    <label class="custom-control-label" for="rdbVisualizacaoPublica">Pública</label>
                </div>
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "R", new { @id = "rdbVisualizacaoRestrita", @class = "custom-control-input" })
                    <label class="custom-control-label" for="rdbVisualizacaoRestrita">Restrita</label>
                </div>
                <br />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 ">
                    <input type="submit" value="Alterar" class="btn btn-primary" />
                    <a href="@Url.Content("/Home/Index")" class="btn btn-outline-dark">Voltar</a>
                </div>
            </div>

            <label class="control-label">
                Associar com Categorias
            </label>

            @if (Model.ListaCategorias != null && Model.ListaCategorias.Count > 0)
            {
                for (int i = 0; i < Model.ListaCategorias.Count; i++)
                {
                    <div class="custom-control custom-checkbox">

                        @Html.HiddenFor(model => Model.ListaCategorias[i].IdCategoria)
                        @Html.HiddenFor(model => Model.ListaCategorias[i].Nome)

                        @Html.CheckBoxFor(model => Model.ListaCategorias[i].Checked, new { id = Model.ListaCategorias[i].IdCategoria,
                            @class = "custom-control-input" })

                        <label class="custom-control-label" for="@Model.ListaCategorias[i].IdCategoria">@Model.ListaCategorias[i].Nome</label>

                    </div>
                }
            }
            else
            {
                <div class="alert alert-primary" role="alert">
                    Nenhuma Categoria cadastrada.
                </div>
            }

        </div>
    </div>
}