TakeaNote.UI/Controllers/CategoriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TakeaNote.Application.Contracts;
using TakeaNote.Domain.DomainEntities;
using TakeaNote.UI.Models;
using TakeaNote.Util.Resources;

namespace TakeaNote.UI.Controllers
{
    [Authorize(Roles = "M, A, U")]
    public class CategoriaController : BaseController
    {
        private readonly ICategoriaAppService categoriaAppService;
        private readonly IFraseAppService fraseAppService;

        public CategoriaController(ICategoriaAppService categoriaAppService, IFraseAppService fraseAppService)
        {
            this.categoriaAppService = categoriaAppService;
            this.fraseAppService = fraseAppService;
        }

        public ActionResult Cadastrar()
        {
            try
            {
                ViewBag.FrasesCollection = ObterFrases();

                return View();
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroCategoriaViewModel model)
        {
            try
            {
                var userSession = Session["USER_SESSION"] as Usuario;

                if (ModelState.IsValid)
                {
                    var frasesCollection = new List<Frase>();

                    if (model.FrasesSelecionadas != null)
                    {
                        foreach (var id in model.FrasesSelecionadas)
                        {
                            var frase = fraseAppService.FindById(int.Parse(id));
                            frasesCollection.Add(frase);
                        }
                    }

                    var categoria = new Categoria
                    {
                        Nome = model.Nome,
                        Descricao = model.Descricao,
                        DataCadastro = DateTime.Now,
                        Visualizacao = model.Visualizacao,
                        // TODO: Prevenir erro ao trazer possivel id nulo num post forçado
                        IdUsuario = userSession.IdUsuario,
                        ListaFrases = frasesCollection
                    };

                    categoriaAppService.Insert(categoria);

                    MensagensSucesso.Add(Resources.CategoriaCadastradaSucesso);

                    ModelState.Clear();
                }
                else
                {
                    MensagensErro = GetModelErrors(ModelState);
                }

                ViewBag.FrasesCollection = fraseAppService.FindAll();
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);
            }

            return View();
        }

        [Authorize(Roles = "M, A, U")]
        public ActionResult Editar(int id)
        {
            try
            {
                var categoria = categoriaAppService.ObterCategoriaComFrases(id);

                var userSession = Session["USER_SESSION"] as Usuario;

                if (userSession.IdUsuario != categoria.IdUsuario)
                {
                    if (userSession.Regra != "M" && userSession.Regra != "A")
                    {
                        throw new Exception(Resources.CategoriaSemPermissaoEdicao);
                    }
                }

                if (categoria != null)
                {
                    // Salva o id atual para prevenir que o usuario nao edite uma categoria diferente da selecionada.

                    Session["ID_CATEGORIA_EDITADA"] = categoria.IdCategoria;

                    var model = new EdicaoCategoriaViewModel
                    {
                        IdCategoria = categoria.IdCategoria,
                        Nome = categoria.Nome,
                        Descricao = categoria.Descricao,
                        Visualizacao = categoria.Visualizacao,
                    };

                    // Recupera as categorias do bd, e associa as categorias ja atribuidas ao Usuario

                    var frasesSelecionadasCollection = new List<FrasesSelecionadasViewModel>();

                    foreach (var item in ObterFrases())
                    {
                        var x = new FrasesSelecionadasViewModel
                        {
                            IdFrase = item.IdFrase,
                            Descricao = item.Descricao
                        };

                        // verificar se a mesma pertence ao Usuario, e marca-la como checked
                        foreach (var fraseUsuario in categoria.ListaFrases)
                        {
                            if (x.IdFrase == fraseUsuario.IdFrase)
                            {
                                x.Checked = true;
                            }
                        }

                        frasesSelecionadasCollection.Add(x);
                    }

                    model.ListaFrases = frasesSelecionadasCollection;

                    return View(model);
                }
                else
                {
                    throw new Exception(Resources.CategoriaErroCarregarDados);
                }
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "M, A, U")]
        [HttpPost]
        public ActionResult Editar(EdicaoCategoriaViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    MensagensErro = GetModelErrors(ModelState);

                    return View(model);
                }

                var listaFrases = new List<Frase>();

                foreach (var frase in model.ListaFrases)
                {
                    if (frase.Checked)
                    {
                        var f = new Frase
                        {
                            IdFrase = frase.IdFrase
                        };

                        listaFrases.Add(f);
                    }
                }

                var categoria = new Categoria
                {
                    // TODO: Prevenir erro ao trazer possivel id nulo num post forçado
                    IdCategoria = (int)Session["ID_CATEGORIA_EDITADA"],
                    Nome = model.Nome,
                    Descricao = model.Descricao,
                    Visualizacao = model.Visualizacao,
                    ListaFrases = listaFrases
                };

                categoriaAppService.AtualizarCategoriaComFrases(categoria);

                MensagensSucesso.Add(Resources.CategoriaAtualizadaSucesso);
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);
            }

            return View(model);
        }

        [Authorize(Roles = "M, A, U, C")]
        public ActionResult Consultar()
        {
            try
            {
                var modelCollection = new List<ConsultaCategoriaViewModel>();

                foreach (var categoria in ObterCategoriasComFrases())
                {
                    var model = new ConsultaCategoriaViewModel
                    {
                        IdCategoria = categoria.IdCategoria,
                        Nome = categoria.Nome,
                        Descricao = categoria.Descricao,
                        DataCadastro = categoria.DataCadastro,
                        Visualizacao = categoria.Visualizacao,
                        ListaFrases = categoria.ListaFrases
                    };

                    modelCollection.Add(model);
                }

                return View(modelCollection);
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "M, A, U")]
        public ActionResult Excluir(int id)
        {
            try
            {
                var categoria = categoriaAppService.ObterCategoriaComFrases(id);

                var userSession = Session["USER_SESSION"] as Usuario;

                if (userSession.IdUsuario != categoria.IdUsuario)
                {
                    if (userSession.Regra != "M" && userSession.Regra != "A")
                    {
                        throw new Exception(Resources.CategoriaSemPermissaoExclusao);
                    }
                }

                categoriaAppService.DeletarCategoria(categoria);

                MensagensSucesso.Add(Resources.CategoriaExcluidaSucesso);

                return RedirectToAction("Consultar");
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        private List<Categoria> ObterCategoriasComFrases()
        {
            try
            {
                return categoriaAppService.ObterCategoriasComFrases();
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }

        private List<Frase> ObterFrases()
        {
            try
            {
                return fraseAppService.ObterFrasesComCategorias();  
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

TakeaNote.UI/Views/Categoria/Cadastrar.cshtml
@model TakeaNote.UI.Models.CadastroCategoriaViewModel

@{
    ViewBag.Title = "Take a Note | Cadastro";
}

@using (Html.BeginForm("Cadastrar", "Categoria", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row mt-5">

        @{ Html.RenderPartial("Mensagens"); }

        <div class="form-horizontal col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label " })
                <div>
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label " })
                <div>
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Visualizacao, htmlAttributes: new { @class = "control-label " })
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "P", new { @id = "rdbVisualizacaoPublica", @class = "custom-control-input", @checked = "checked" })
                    <label class="custom-control-label" for="rdbVisualizacaoPublica">Pública</label>
                </div>
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "R", new { @id = "rdbVisualizacaoRestrita", @class = "custom-control-input" })
                    <label class="custom-control-label" for="rdbVisualizacaoRestrita">Restrita</label>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 ">
                    <input type="submit" value="Cadastrar" class="btn btn-primary" />
                    <a href="@Url.Content("/Home/Index")" class="btn btn-outline-dark">Voltar</a>
                </div>
            </div>

            <label class="control-label">
                Associar com Frases
            </label>

            @if (ViewBag.FrasesCollection != null && ViewBag.FrasesCollection.Count > 0)
            {
                foreach (var item in ViewBag.FrasesCollection)
                {
                    <div class="custom-control custom-checkbox">
                        <input class="custom-control-input" id="@item.IdFrase" type="checkbox" name="FrasesSelecionadas" value="@item.IdFrase" />
                        <label class="custom-control-label" for="@item.IdFrase">@item.Descricao</label>
                    </div>
                }
            }

        </div>
    </div>
}

TakeaNote.UI/Views/Categoria/Consultar.cshtml
@using TakeaNote.Domain.DomainEntities

@{
    Usuario usuario = Session["USER_SESSION"] as Usuario;
    ViewBag.Title = "Take a Note | Consultar Categorias";
    string corBadge = "";
}

@model IEnumerable<TakeaNote.UI.Models.ConsultaCategoriaViewModel>

<div class="row mt-5">

    @{ Html.RenderPartial("Mensagens"); }

    <div class="form-horizontal col-md-12">

        @foreach (var categoria in Model)
        {
            if (categoria.Visualizacao == "P")
            {
                corBadge = "alert-info";
            }
            else
            {
                corBadge = "alert-danger";
            }

            <div id="accordion">
                <div class="card shadow">
                    <div class="card-header bg-transparent" id="heading_@categoria.IdCategoria" style="padding-bottom:5px; padding-top:10px">
                        <h6 class="mb-0">
                            <btn class="btn btn-link text-dark" style="text-decoration:none" data-toggle="collapse" data-target="#linha_@categoria.IdCategoria" aria-expanded="true" aria-controls="linha_@categoria.IdCategoria">
                                @categoria.Nome
                            </btn>
                            <span class="badge badge-pill float-right @corBadge">
                                @categoria.Visualizacao
                            </span>
                        </h6>
                    </div>

                    <div id="linha_@categoria.IdCategoria" class="collapse" aria-labelledby="heading_@categoria.IdCategoria" data-parent="#accordion">
                        <div class="card-body">
                            <span class="card-subtitle mb-2 text-muted">@categoria.Descricao</span>
                            <hr />

                            <div>
                                <ul class="list-group">
                                    @foreach (var frase in categoria.ListaFrases)
                                    {
                                        <li class="list-group-item">
                                            @frase.Descricao
                                        </li>
                                    }
                                </ul>
                            </div>
                            <hr />

                            <a href="@Url.Action("Editar", "Categoria", new { id = categoria.IdCategoria })" class="btn btn-sm btn-primary">Editar</a>

                            @Html.ActionLink("Excluir", "Excluir",
                                new { id = categoria.IdCategoria },
                                new { onclick = "return confirm('Tem certeza que deseja excluir?')", @class = "btn btn-sm btn-dark" })
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

TakeaNote.UI/Views/Categoria/Editar.cshtml
@using TakeaNote.Domain.DomainEntities

@{
    Usuario usuario = Session["USER_SESSION"] as Usuario;
}

@model TakeaNote.UI.Models.EdicaoCategoriaViewModel

@{
    ViewBag.Title = "Take a Note | Editar Categoria";
}

@using (Html.BeginForm("Editar", "Categoria", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row mt-5">

        @{ Html.RenderPartial("Mensagens"); }

        <div class="form-horizontal col-md-10">

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", @type = "text", autofocus = "autofocus" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Visualizacao, htmlAttributes: new { @class = "control-label " })
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "P", new { @id = "rdbVisualizacaoPublica", @class = "custom-control-input" })
                    <label class="custom-control-label" for="rdbVisualizacaoPublica">Pública</label>
                </div>
                <br />
                <div class="custom-control custom-radio custom-control-inline">
                    @Html.RadioButtonFor(model => model.Visualizacao, "R", new { @id = "rdbVisualizacaoRestrita", @class = "custom-control-input" })
                    <label class="custom-control-label" for="rdbVisualizacaoRestrita">Restrita</label>
                </div>
                <br />
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 ">
                    <input type="submit" value="Alterar" class="btn btn-primary" />
                    <a href="@Url.Content("/Home/Index")" class="btn btn-outline-dark">Voltar</a>
                </div>
            </div>

            <label class="control-label">
                Associar com Frases
            </label>

            @if (Model.ListaFrases != null && Model.ListaFrases.Count > 0)
            {
                for (int i = 0; i < Model.ListaFrases.Count; i++)
                {
                    <div class="custom-control custom-checkbox">

                        @Html.HiddenFor(model => Model.ListaFrases[i].IdFrase)
                        @Html.HiddenFor(model => Model.ListaFrases[i].Descricao)

                        @Html.CheckBoxFor(model => Model.ListaFrases[i].Checked, new { id = Model.ListaFrases[i].IdFrase,
                            @class = "custom-control-input" })

                        <label class="custom-control-label" for="@Model.ListaFrases[i].IdFrase">@Model.ListaFrases[i].Descricao</label>

                    </div>
                }
            }
            else
            {
                <div class="alert alert-primary" role="alert">
                    Nenhuma Frase cadastrada.
                </div>
            }

        </div>
    </div>
}