TakeaNote.UI/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TakeaNote.Application.Contracts;
using TakeaNote.Domain.DomainEntities;
using TakeaNote.UI.Models;
using TakeaNote.Util.Resources;

namespace TakeaNote.UI.Controllers
{
    public class UsuarioController : BaseController
    {
        private readonly IUsuarioAppService usuarioAppService;
        private readonly IFraseAppService fraseAppService;
        private readonly ICategoriaAppService categoriaAppService;

        public UsuarioController(IUsuarioAppService usuarioAppService, IFraseAppService fraseAppService,
            ICategoriaAppService categoriaAppService)
        {
            this.usuarioAppService = usuarioAppService;
            this.fraseAppService = fraseAppService;
            this.categoriaAppService = categoriaAppService;
        }

        public ActionResult Cadastrar()
        {
            // TODO: Exibir Dashboard
            // TODO: Remover JS desnecessários (JQuery Validade?)

            return View();
        }

        [HttpPost]
        public ActionResult Cadastrar(CadastroUsuarioViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    MensagensErro = GetModelErrors(ModelState);

                    return View();
                }

                var usuario = new Usuario
                {
                    Nome = model.Nome,
                    Login = model.Login,
                    Email = model.Email,
                    Senha = model.Senha
                };

                usuarioAppService.Insert(usuario);

                MensagensSucesso.Add(Resources.UsuarioCadastradoSucesso);

                ModelState.Clear();
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);
            }

            return View();
        }

        [Authorize(Roles = "M, A, U")]
        public ActionResult Editar(int id)
        {
            try
            {
                var usuario = usuarioAppService.FindById(id);

                var userSession = Session["USER_SESSION"] as Usuario;

                if (userSession.IdUsuario != usuario.IdUsuario 
                    && userSession.Regra != "M" 
                    && userSession.Regra != "A")
                {
                    throw new Exception(Resources.UsuarioSemPermissaoEdicao);
                }

                if (usuario != null)
                {
                    // Exibe na pagina somente campos que podem ser alterados
                    var model = new EdicaoUsuarioViewModel
                    {
                        Nome = usuario.Nome,
                        Login = usuario.Login,
                        Email = usuario.Email,
                        Regra = usuario.Regra
                    };

                    // Salva o Usuario no tempdata para posterior comparacao
                    TempData["USER_TEMP"] = usuario;

                    return View(model);
                }
                else
                {
                    throw new Exception(Resources.UsuarioErroCarregarDados);
                }
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "M, A, U")]
        [HttpPost]
        public ActionResult Editar(EdicaoUsuarioViewModel model)
        {
            try
            {
                var userSession = Session["USER_SESSION"] as Usuario;
                var userTemp = TempData["USER_TEMP"] as Usuario;

                if (userSession.Regra != "M" 
                    && userTemp.Login != model.Login)
                {
                    throw new Exception(Resources.CampoLoginNaoEditavel);
                }

                if (!ModelState.IsValid)
                {
                    MensagensErro = GetModelErrors(ModelState);

                    return View();
                }

                // TODO: Estudar como colocar esta validação dentro das validações na ModelState
                if (!string.IsNullOrEmpty(model.NovaSenha) 
                    && string.IsNullOrEmpty(model.SenhaAtual))
                {
                    MensagensErro.Add(Resources.CampoNovaSenhaPreenchido);
                }

                var usuario = new Usuario
                {
                    IdUsuario = userTemp.IdUsuario,
                    Nome = model.Nome,
                    Login = model.Login,
                    Email = model.Email,
                    DataCadastro = userTemp.DataCadastro,

                    Regra = string.IsNullOrEmpty(model.Regra) ? userTemp.Regra : model.Regra,
                    Senha = usuarioAppService.ValidarTrocaSenha(userTemp.Senha, model.SenhaAtual, model.NovaSenha)
                };

                usuarioAppService.Update(usuario);

                MensagensSucesso.Add(Resources.UsuarioAtualizadoSucesso);
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);
            }

            return View();
        }

        [Authorize(Roles = "M, A")]
        public ActionResult Consultar()
        {
            try
            {
                return View(CarregarUsuarios());
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        [Authorize(Roles = "M, A")]
        public ActionResult Excluir(int id)
        {
            try
            {
                fraseAppService.DeletarFrasesUsuario(id);
                categoriaAppService.DeletarCategoriasUsuario(id);

                var usuario = usuarioAppService.FindById(id);

                usuarioAppService.Delete(usuario);

                MensagensSucesso.Add(Resources.UsuarioExcluidoSucesso);

                return RedirectToAction("Consultar");
            }
            catch (Exception ex)
            {
                MensagensErro.Add(ex.Message);

                return RedirectToAction("Index", "Home");
            }
        }

        private List<ConsultaUsuarioViewModel> CarregarUsuarios()
        {
            try
            {
                var listaModel = new List<ConsultaUsuarioViewModel>();

                foreach (var usuario in usuarioAppService.FindAll())
                {
                    var model = new ConsultaUsuarioViewModel
                    {
                        IdUsuario = usuario.IdUsuario,
                        Nome = usuario.Nome,
                        Login = usuario.Login,
                        Email = usuario.Email,
                        Senha = usuario.Senha,
                        DataCadastro = usuario.DataCadastro,
                        Regra = usuario.Regra,
                        TotalFrases = fraseAppService.ObterTotalFrasesPorUsuario(usuario.IdUsuario),
                        TotalCategorias = categoriaAppService.ObterTotalCategoriasPorUsuario(usuario.IdUsuario)
                    };

                    listaModel.Add(model);
                }

                return listaModel;
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
        }
    }
}

TakeaNote.UI/Views/Usuario/Cadastrar.cshtml
@model TakeaNote.UI.Models.CadastroUsuarioViewModel

@{
    ViewBag.Title = "Take a Note | Cadastro";
}

@using (Html.BeginForm("Cadastrar", "Usuario", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
<div class="row mt-5">

    @{ Html.RenderPartial("Mensagens"); }

    <div class="form-horizontal col-md-4 ">

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label " })
            <div class="">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label " })
            <div class="">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label " })
            <div class="">
                @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Senha, htmlAttributes: new { @class = "control-label " })
            <div class="">
                @Html.EditorFor(model => model.Senha, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 ">
                <input type="submit" value="Cadastrar" class="btn btn-primary" />
                <a href="@Url.Content("/Login/Index")" class="btn btn-outline-dark">Voltar</a>
            </div>
        </div>
    </div>
</div>
}

TakeaNote.UI/Views/Usuario/Consultar.cshtml
@using TakeaNote.Domain.DomainEntities

@{
    Usuario usuario = Session["USER_SESSION"] as Usuario;
}

@model IEnumerable<TakeaNote.UI.Models.ConsultaUsuarioViewModel>

@{
    ViewBag.Title = "Take a Note | Gerenciar Usuários";
}

<div class="row mt-5">

    @{ Html.RenderPartial("Mensagens"); }

    <div class="table-responsive shadow">
        <table class="table table-hover">
            <thead class="bg-dark text-light">
                <tr>
                    <th>Id</th>
                    <th>Nome</th>
                    <th>Login</th>
                    <th>Email</th>
                    <th>Regra</th>
                    <th>Frases</th>
                    <th>Categorias</th>
                    <th>Operações</th>
                </tr>
            </thead>
            <tbody class="bg-white">
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IdUsuario)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Nome)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Login)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Regra)
                        </td>
                        <td>
                            <span class="badge badge-pill badge-dark">
                                @Html.DisplayFor(modelItem => item.TotalFrases)
                            </span>
                        </td>
                        <td>
                            <span class="badge badge-pill badge-dark">
                                @Html.DisplayFor(modelItem => item.TotalCategorias)
                            </span>
                        </td>
                        <td>
                            <a href="@Url.Action("Editar", "Usuario", new { id = item.IdUsuario })" class="btn btn-sm btn-primary">Editar</a>

                            @Html.ActionLink("Excluir", "Excluir",
                                new { id = item.IdUsuario },
                                new { onclick = "return confirm('Isto irá apagar todos as Frases e Categorias associadas a este Usuário. Tem certeza que deseja excluir?')", @class = "btn btn-sm btn-dark" })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

TakeaNote.UI/Views/Usuario/Editar.cshtml
@using TakeaNote.Domain.DomainEntities

@{
    Usuario usuario = Session["USER_SESSION"] as Usuario;
}

@model TakeaNote.UI.Models.EdicaoUsuarioViewModel

@{
    ViewBag.Title = "Take a Note | Editar Usuário";
}

@using (Html.BeginForm("Editar", "Usuario", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    <div class="row mt-5">

        @{ Html.RenderPartial("Mensagens"); }

        <div class="form-horizontal col-md-4 ">

            <div class="form-group">
                @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control", autofocus = "autofocus" } })
                </div>
            </div>

            @if (usuario.Regra == "M")
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label " })
                    <div class="">
                        @Html.EditorFor(model => model.Login, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            }
            else
            {
                <div class="form-group">
                    @Html.LabelFor(model => model.Login, htmlAttributes: new { @class = "control-label " })
                    <div class="">
                        @Html.TextBoxFor(model => model.Login, new { @class = "form-control", @readonly = "readonly" })
                    </div>
                </div>
            }

            <div class="form-group">
                @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @type = "text" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SenhaAtual, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.SenhaAtual, new { htmlAttributes = new { @class = "form-control", @type = "password", @Value = "", @placeholder = "Senha inalterada" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NovaSenha, htmlAttributes: new { @class = "control-label " })
                <div class="">
                    @Html.EditorFor(model => model.NovaSenha, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                </div>
            </div>

            @if (usuario.Regra == "M")
            {
                <div class="form-group">
                    <label>Regra</label>
                    <br />
                    <div class="custom-control custom-radio custom-control-inline">
                        @Html.RadioButtonFor(model => model.Regra, "C", new { @id = "rdbRegraConvidado", @class = "custom-control-input" })
                        <label class="custom-control-label" for="rdbRegraConvidado">Convidado</label>
                    </div>
                    <br />
                    <div class="custom-control custom-radio custom-control-inline">
                        @Html.RadioButtonFor(model => model.Regra, "U", new { @id = "rdbRegraUsuario", @class = "custom-control-input" })
                        <label class="custom-control-label" for="rdbRegraUsuario">Usuário</label>
                    </div>
                    <br />
                    <div class="custom-control custom-radio custom-control-inline">
                        @Html.RadioButtonFor(model => model.Regra, "A", new { @id = "rdbRegraAdministrador", @class = "custom-control-input" })
                        <label class="custom-control-label" for="rdbRegraAdministrador">Administrador</label>
                    </div>
                    <br />
                    <div class="custom-control custom-radio custom-control-inline">
                        @Html.RadioButtonFor(model => model.Regra, "M", new { @id = "rdbRegraMaster", @class = "custom-control-input" })
                        <label class="custom-control-label" for="rdbRegraMaster">Master</label>
                    </div>
                </div>
            }

            <div class="form-group">
                <div>
                    <input type="submit" value="Alterar" class="btn btn-primary" />
                    <a href="@Url.Content("/Usuario/Consultar")" class="btn btn-outline-dark">Voltar</a>
                </div>
            </div>
        </div>
    </div>
}